export const musicStyles = [
  { id: 'latin', label: { es: 'Latina', en: 'Latin', de: 'Latin' } },
  { id: 'reggaeton', label: { es: 'Reggaeton', en: 'Reggaeton', de: 'Reggaeton' } },
  { id: 'pop', label: { es: 'Pop', en: 'Pop', de: 'Pop' } },
  { id: 'house', label: { es: 'House', en: 'House', de: 'House' } },
  { id: 'electronic', label: { es: 'Electrónica', en: 'Electronic', de: 'Elektronisch' } },
  { id: 'hiphop', label: { es: 'Hip Hop', en: 'Hip Hop', de: 'Hip Hop' } },
  { id: 'rock', label: { es: 'Rock', en: 'Rock', de: 'Rock' } },
  { id: 'rnb', label: { es: 'R&B', en: 'R&B', de: 'R&B' } },
  { id: 'jazz', label: { es: 'Jazz', en: 'Jazz', de: 'Jazz' } },
  { id: 'salsa', label: { es: 'Salsa', en: 'Salsa', de: 'Salsa' } },
  { id: 'bachata', label: { es: 'Bachata', en: 'Bachata', de: 'Bachata' } },
  { id: 'merengue', label: { es: 'Merengue', en: 'Merengue', de: 'Merengue' } },
  { id: 'cumbia', label: { es: 'Cumbia', en: 'Cumbia', de: 'Cumbia' } },
  { id: '80s', label: { es: '80s', en: '80s', de: '80er' } },
  { id: '90s', label: { es: '90s', en: '90s', de: '90er' } },
  { id: '2000s', label: { es: '2000s', en: '2000s', de: '2000er' } },
  { id: '2010s', label: { es: '2010s', en: '2010s', de: '2010er' } },
  { id: 'current', label: { es: 'Actual', en: 'Current', de: 'Aktuell' } },
  { id: 'classic', label: { es: 'Clásica', en: 'Classic', de: 'Klassisch' } },
  { id: 'disco', label: { es: 'Disco', en: 'Disco', de: 'Disco' } },
  { id: 'schlager', label: { es: 'Schlager', en: 'Schlager', de: 'Schlager' } },
  { id: 'ballermann', label: { es: 'Ballermann', en: 'Ballermann', de: 'Ballermann' } },
  { id: 'volksmusik', label: { es: 'Música Popular Alemana', en: 'German Folk Music', de: 'Volksmusik' } },
  { id: 'techno', label: { es: 'Techno', en: 'Techno', de: 'Techno' } },
  { id: 'trance', label: { es: 'Trance', en: 'Trance', de: 'Trance' } }
];
